--INICIO DDL

CREATE DATABASE Gufi
GO

USE Gufi
GO

--INICIO TABELAS INDEPENDENTES

CREATE TABLE Instituiçao(
idInstituiçao TINYINT PRIMARY KEY IDENTITY (1,1),
CNPJ CHAR(11) NOT NULL,
nomeFantasia VARCHAR (20) NOT NULL,
endereço VARCHAR (30) NOT NULL,
);

CREATE TABLE Categoria(
idCategoria TINYINT PRIMARY KEY IDENTITY (1,1),
nomeTipoEve VARCHAR (10) NOT NULL,
);

CREATE TABLE Tipo_Usuario(
idTipo_User TINYINT PRIMARY KEY IDENTITY (1,1),
nomeTipoUser VARCHAR (18) NOT NULL,
);

CREATE TABLE Situaçao(
idSituaçao  TINYINT PRIMARY KEY IDENTITY (1,1),
desccrição TEXT NOT NULL,
);

--FIM TABELAS DEPENDENTES
--INICIO DAS TABELAS DEPENDENTES

CREATE TABLE Usuarios(
idUser TINYINT PRIMARY KEY IDENTITY (1,1),
nomeUser VARCHAR (35) NOT NULL,
email VARCHAR (22) NOT NULL,
senha VARCHAR (11) NOT NULL,
endereço VARCHAR (30) NOT NULL,
);

CREATE TABLE Eventos(
idEvento SMALLINT PRIMARY KEY IDENTITY (1,1),
idCategoria TINYINT FOREIGN KEY REFERENCES Categoria(idCategoria), 
idInstituiçao TINYINT FOREIGN KEY REFERENCES Instituiçao(idInstituiçao),
titulo VARCHAR (10) NOT NULL,
acesso VARCHAR (16) NOT NULL,
diaEvento DATETIME NOT NULL,
descriçao TEXT NOT NULL,
);

CREATE TABLE Presenças(
idPresença INT PRIMARY KEY IDENTITY (1,1),
idUser TINYINT FOREIGN KEY REFERENCES Usuarios(idUser),
idEvento SMALLINT FOREIGN KEY REFERENCES Eventos(idEvento),
idCategoria TINYINT FOREIGN KEY REFERENCES Categoria(idCategoria),
);

--UTILIZEI O INT AQUI POIS NÃO SABIA SE O SISTEMA MATERIA O DADO DOS USUARIOS SALVOS PARA SEMPRE OU SE COM O TEMPO QUE O LIMITE DE REGISTROS
--FOSSE ALCANÇADO O SISTEMA ACABARIA ARMAZENANDO OS DADOS DAS PESSOAS JA CADASTRADAS EM OUTRO LOCAL E APÓS ISSO IRIA PREENCHER NOVAMENTE SEUS 
--CAMPOS!

--FIM TABELAS DEPENDENTES